name: "Run Docs CD"

on:
  push:
    branches:
      - "main"
      - "chore-docs-search-fix"  # FIX remove tmp condition

jobs:
  build-deploy-docs:
    uses: ./.github/workflows/docs.yml
    with:
      deploy: true
    permissions:
      contents: write
