name: "Run CI"

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - "**"
      - "!main"
      - "!gh-pages"

env:
  # disable keyring (https://github.com/actions/runner-images/issues/6185):
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  code-checks:
    uses: ./.github/workflows/checks.yml

    # To enable when we add the ./docs
  # build-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/setup-poetry
  #     - name: Build docs
  #       run: poetry run mkdocs build --verbose --clean
  