name: "Run CI"

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - "**"
      - "!main"
      - "!gh-pages"

env:
  # disable keyring (https://github.com/actions/runner-images/issues/6185):
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  code-checks:
    uses: ./.github/workflows/checks.yml
  build-docs:
    uses: ./.github/workflows/docs.yml
    with:
      deploy: false
